Repository fxamacker/cbor, pull requests merged in 2023-11, with the labels that each got.

#433 Add FieldNameMatching decode option.
  decode.go
  decode_test.go
Labels: enhancement

#434 Refactor valid() to reject negative values for integer modes
  decode.go
  decode_test.go
  doc.go
  encode.go
  encode_test.go
  tag.go
Labels: improvement

#437 Enable more linters
  .golangci.yml
  encode.go
  simplevalue.go
  structfields.go
Labels: CI
