Repository fxamacker/cbor, pull requests merged in 2023-05, with the labels that each got.

#400 Deprecate Valid() and add Wellformed() to replace it
  decode.go
  stream.go
  valid.go
  valid_test.go
Labels: enhancement

#402 Add UnmarshalFirst to DecMode interface
  decode.go
  decode_test.go
Labels: enhancement

#386 Implements diagnostic notation (#384)
  diagnose.go
  diagnose_test.go
Labels: enhancement

#405 Add more tests for Diagnose and DiagnoseFirst
  README.md
  diagnose_test.go
Labels: tests

#406 Update README for CBOR Sequences RFC 8742
  README.md
Labels: docs

#407 Update README.md for v2.5.0-beta3
  README.md
Labels: docs

#408 Bump safer-golangci-lint to 1.52.2
  .github/workflows/safer-golangci-lint.yml
  .golangci.yml
  README.md
Labels: CI
