Repository fxamacker/cbor, pull requests merged in 2024-01, with the labels that each got.

#461 Fix panic when decoding CBOR nil to `*cbor.SimpleValue`
  decode.go
  decode_test.go
Labels: bugfix

#464 Fix cbor.SimpleValue encoding and decoding
  decode.go
  decode_test.go
  encode.go
  simplevalue.go
  simplevalue_test.go
Labels: bugfix

#453 Add encoding option to specify how omitempty fields are encoded
  encode.go
  encode_test.go
Labels: enhancement

#466 Add another test and fix lint errors
  encode.go
  encode_test.go
Labels: tests
