Repository fxamacker/cbor, pull requests merged in 2024-02, with the labels that each got.

#480 Fix EncOption/DecOption unset fields on mode regurgitation.
  decode.go
  decode_test.go
  encode.go
  encode_test.go
Labels: bugfix

#484 Add `UnrecognizedTagToAny` option to `TestDecOptions`
  decode_test.go
Labels: tests

#493 Bump govulncheck from v1.0.1 to v1.0.4
  .github/workflows/govulncheck.yml
Labels: CI

#485 Check well-formedness of data from MarshalCBOR
  decode.go
  diagnose.go
  encode.go
  encode_test.go
  stream.go
  tag_test.go
  valid.go
  valid_test.go
Labels: bugfix
