Repository fxamacker/cbor, pull requests merged in 2024-05, with the labels that each got.

#519 Encode structs directly to output buffer.
  bench_test.go
  cache.go
  encode.go
  encode_test.go
Labels: performance

#531 Refactor to reuse functions and improve code coverage
  cache.go
  encode.go
Labels: improvement

#542 Refactor and improve code
  bench_test.go
  cache.go
  common.go
  decode.go
  decode_test.go
  diagnose.go
  encode.go
  encode_test.go
  simplevalue.go
  stream.go
  stream_test.go
  structfields.go
  tag.go
  tag_test.go
  valid.go
Labels: improvement

#543 Bump golangci-lint from 1.53.3 to 1.54.2
  .github/workflows/safer-golangci-lint.yml
  .golangci.yml
Labels: CI

#544 Use "cbor:" prefixed error msg when decoding with non-default TimeTagToAnyMode setting
  decode.go
  decode_test.go
  encode.go
Labels: improvement
