Repository fxamacker/cbor, pull requests merged in 2025-03, with the labels that each got.

#636 Update error handling in RawTag.UnmarshalCBOR(), etc. to match cbor.Unmarshal()
  bytestring.go
  bytestring_test.go
  simplevalue.go
  simplevalue_test.go
  tag.go
  tag_test.go
Labels: bugfix

#644 Add omitzero support
  README.md
  cache.go
  doc.go
  encode.go
  encode_map.go
  encode_test.go
  omitzero_go124.go
  omitzero_pre_go124.go
  structfields.go
Labels: enhancement

#645 Port updated error handling in RawTag.UnmarshalCBOR(), etc. to match cbor.Unmarshal()
  bytestring.go
  bytestring_test.go
  simplevalue.go
  simplevalue_test.go
  tag.go
  tag_test.go
Labels: bugfix

#647 Optimize internal calls to UnmarshalCBOR() for ByteString, RawTag, SimpleValue
  bytestring.go
  bytestring_test.go
  cache.go
  decode.go
  simplevalue.go
  simplevalue_test.go
  tag.go
  tag_test.go
Labels: performance

#648 Port PR 647 to release-2.7 branch to optimize internal calls to UnmarshalCBOR()
  bytestring.go
  bytestring_test.go
  cache.go
  decode.go
  simplevalue.go
  simplevalue_test.go
  tag.go
  tag_test.go
Labels: performance

#649 Update docs for cbor v2.8.0
  README.md
  doc.go
  example_test.go
Labels: docs
